INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('1', 'AMAZONAS',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('2', 'ANTIOQUIA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('3', 'ARAUCA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('4', 'ATLÁNTICO',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('5', 'BOLÍVAR',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('6', 'BOYACÁ',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('7', 'CALDAS',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('8', 'CAQUETÁ',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('9', 'CASANARE',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('10', 'CAUCA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('11', 'CESAR',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('12', 'CHOCÓ',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('13', 'CÓRDOBA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('14', 'CUNDINAMARCA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('15', 'GUAINÍA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('16', 'GUAVIARE',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('17', 'HUILA',1);
INSERT INTO departamento (departamento_id, nombre , pais_id) VALUES ('18', 'LA GUAJIRA',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('19', 'MAGDALENA',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('20', 'META',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('21', 'NARIÑO', 1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('22', 'NORTE DE SANTANDER',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('23', 'PUTUMAYO',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('24', 'QUINDÍO',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('25', 'RISARALDA',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('26', 'SAN ANDRÉS Y ROVIDENCIA',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('27', 'SANTANDER',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('28', 'SUCRE',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('29', 'TOLIMA',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('30', 'VALLE DEL CAUCA',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('31', 'VAUPÉS',1);
INSERT INTO departamento (departamento_id, nombre, pais_id) VALUES ('32', 'VICHADA',1);